create_app: catch config errors
This makes the server logs contain:

[ERROR] Could not import python object: nowhere.found

instead of a long backtrace ending
with:

datacube_ows.config_utils.ConfigException: Could not import python object: nowhere.found